[workspace]
members = [
    "rai",
    "rai-core",
    "rai-nn",
    "examples/*"
]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = ["science"]

[workspace.dependencies]
rai-core = { path = "rai-core", version = "0.3.0" }
rai-nn = { path = "rai-nn", version = "0.3.0" }
candle-core = "0.3.1"
dyn-clone = "1.0.16"
once_cell = "1.19.0"
thiserror = "1.0.51"
tracing = "0.1.40"
